cmake_minimum_required(VERSION 3.20)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef SB_SUFFIX)
set(SB_ROOT "${SB_TEST_ROOT}/${SB_SUFFIX}")
file(MAKE_DIRECTORY "${SB_ROOT}/source" "${SB_ROOT}/assets")
file(WRITE "${SB_ROOT}/source/CMakeLists.txt" "project(SecondBrain VERSION 0.7.3 LANGUAGES C)\n")
function(sb_expect SB_OK)
    execute_process(COMMAND "${CMAKE_COMMAND}" ${ARGN} RESULT_VARIABLE SB_RESULT OUTPUT_QUIET ERROR_QUIET)
    if((SB_OK AND NOT SB_RESULT EQUAL 0) OR (NOT SB_OK AND SB_RESULT EQUAL 0))
        message(FATAL_ERROR "Release guard returned unexpected result: ${ARGN}")
    endif()
endfunction()
set(SB_TAG_TOOL "${SB_SOURCE_ROOT}/tools/check_prerelease_tag.cmake")
sb_expect(TRUE "-DSB_TAG=v0.7.3" "-DSB_SOURCE_ROOT=${SB_ROOT}/source" -P "${SB_TAG_TOOL}")
foreach(SB_BAD IN ITEMS v1.0.0 v0.7.2 v0.07.3 v0.7.3-dev main)
    sb_expect(FALSE "-DSB_TAG=${SB_BAD}" "-DSB_SOURCE_ROOT=${SB_ROOT}/source" -P "${SB_TAG_TOOL}")
endforeach()
set(SB_ASSET_TOOL "${SB_SOURCE_ROOT}/tools/release_assets.cmake")
set(SB_ARGS "-DSB_VERSION=0.7.3" "-DSB_ASSET_DIR=${SB_ROOT}/assets")
foreach(SB_FILE IN ITEMS SecondBrain-0.7.3-Windows-AMD64.zip SecondBrain-0.7.3-Darwin-arm64.tar.gz SecondBrain-0.7.3-Darwin-x86_64.tar.gz SecondBrain-0.7.3-Linux-x86_64.tar.gz)
    file(WRITE "${SB_ROOT}/assets/${SB_FILE}" "Fixture ${SB_FILE}")
endforeach()
sb_expect(TRUE ${SB_ARGS} -P "${SB_ASSET_TOOL}")
file(COPY "${SB_ROOT}/assets/SHA256SUMS" DESTINATION "${SB_ROOT}/expected")
sb_expect(FALSE ${SB_ARGS} -P "${SB_ASSET_TOOL}")
set(SB_VERIFY_ARGS ${SB_ARGS} -DSB_VERIFY=ON "-DSB_EXPECTED_SUMS=${SB_ROOT}/expected/SHA256SUMS")
sb_expect(TRUE ${SB_VERIFY_ARGS} -P "${SB_ASSET_TOOL}")
file(APPEND "${SB_ROOT}/assets/SecondBrain-0.7.3-Windows-AMD64.zip" "changed")
sb_expect(FALSE ${SB_VERIFY_ARGS} -P "${SB_ASSET_TOOL}")
file(WRITE "${SB_ROOT}/assets/SecondBrain-0.7.3-Linux-extra.tar.gz" "extra")
sb_expect(FALSE ${SB_VERIFY_ARGS} -P "${SB_ASSET_TOOL}")
file(REMOVE "${SB_ROOT}/assets/SecondBrain-0.7.3-Linux-extra.tar.gz" "${SB_ROOT}/assets/SecondBrain-0.7.3-Linux-x86_64.tar.gz")
sb_expect(FALSE ${SB_VERIFY_ARGS} -P "${SB_ASSET_TOOL}")
message(STATUS "Release contract passed: development-only tags, version match, required packages, hashes and overwrite protection")
