cmake_minimum_required(VERSION 3.20)
if(NOT SB_CLI OR NOT SB_TEST_ROOT)
    message(FATAL_ERROR "SB_CLI and SB_TEST_ROOT are required")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run)
set(root "${SB_TEST_ROOT}/${run}")
set(workspace "${root}/Arbeitsordner ü")
set(restore "${root}/Wiederhergestellt ü")
set(archive "${root}/Sicherung ü.sbbackup")
file(MAKE_DIRECTORY "${restore}")
function(invoke)
    execute_process(COMMAND "${SB_CLI}" ${ARGV} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "CLI failed: ${ARGV}\n${output}\n${error}")
    endif()
endfunction()
invoke(new "${workspace}" projekt "Projekt ü")
set(note "${workspace}/projekt/knowledge/test.md")
file(WRITE "${note}" "# Wiederherstellung ü\n\nEine gespeicherte Erkenntnis.\n")
invoke(backup "${workspace}" projekt "${archive}")
file(SHA256 "${archive}" original_hash)
invoke(inspect "${archive}")
invoke(restore "${archive}" "${restore}" kopie)
file(SHA256 "${note}" before)
file(SHA256 "${restore}/kopie/knowledge/test.md" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "The saved note was not restored byte for byte")
endif()
file(READ "${restore}/kopie/brain.json" identity)
if(NOT identity MATCHES "\"id\": \"kopie\"")
    message(FATAL_ERROR "Restored project identity does not match the chosen folder")
endif()
execute_process(COMMAND "${SB_CLI}" restore "${archive}" "${restore}" kopie
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET TIMEOUT 60)
if(result EQUAL 0)
    message(FATAL_ERROR "Restore replaced an existing project")
endif()
execute_process(COMMAND "${SB_CLI}" backup "${workspace}" projekt "${archive}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET TIMEOUT 60)
file(SHA256 "${archive}" preserved_hash)
if(result EQUAL 0 OR NOT original_hash STREQUAL preserved_hash)
    message(FATAL_ERROR "An existing backup was overwritten")
endif()
message(STATUS "Production CLI preserved, inspected and restored a backup with Unicode paths")
