cmake_minimum_required(VERSION 3.20)
if(NOT SB_CLI OR NOT SB_TEST_ROOT)
    message(FATAL_ERROR "CLI and private test root required")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef SB_SUFFIX)
set(SB_ROOT "${SB_TEST_ROOT}/${SB_SUFFIX}/Arbeitsordner ü")
foreach(SB_ID IN ITEMS good bad)
    execute_process(COMMAND "${SB_CLI}" new "${SB_ROOT}" "${SB_ID}" "Projekt ${SB_ID}"
        RESULT_VARIABLE SB_RESULT OUTPUT_QUIET ERROR_VARIABLE SB_ERROR)
    if(NOT SB_RESULT EQUAL 0)
        message(FATAL_ERROR "Fixture creation failed: ${SB_ERROR}")
    endif()
endforeach()
set(SB_BAD "{\"name\":\"Defekt\",\"schema_version\":2}")
file(WRITE "${SB_ROOT}/bad/brain.json" "${SB_BAD}")
execute_process(COMMAND "${SB_CLI}" list "${SB_ROOT}" RESULT_VARIABLE SB_RESULT
    OUTPUT_VARIABLE SB_OUTPUT ERROR_VARIABLE SB_ERROR)
if(NOT SB_RESULT EQUAL 1 OR NOT SB_OUTPUT MATCHES "good" OR SB_OUTPUT MATCHES "bad" OR NOT SB_ERROR MATCHES "bad:.*Projektschema 2")
    message(FATAL_ERROR "Partial CLI list contract failed: ${SB_RESULT}; ${SB_OUTPUT}; ${SB_ERROR}")
endif()
execute_process(COMMAND "${SB_CLI}" context "${SB_ROOT}" good RESULT_VARIABLE SB_RESULT
    OUTPUT_VARIABLE SB_OUTPUT ERROR_VARIABLE SB_ERROR)
if(NOT SB_RESULT EQUAL 0 OR NOT SB_OUTPUT MATCHES "PROJECT.md")
    message(FATAL_ERROR "Independent project context failed: ${SB_ERROR}")
endif()
execute_process(COMMAND "${SB_CLI}" context "${SB_ROOT}" bad RESULT_VARIABLE SB_RESULT
    OUTPUT_QUIET ERROR_VARIABLE SB_ERROR)
if(NOT SB_RESULT EQUAL 1 OR NOT SB_ERROR MATCHES "Projektschema 2")
    message(FATAL_ERROR "Blocked project diagnostic failed: ${SB_ERROR}")
endif()
file(READ "${SB_ROOT}/bad/brain.json" SB_PRESERVED)
if(NOT SB_PRESERVED STREQUAL SB_BAD)
    message(FATAL_ERROR "Blocked metadata changed")
endif()
message(STATUS "Production CLI preserves blocked metadata and reports partial discovery")
