cmake_minimum_required(VERSION 3.20)
if(NOT SB_ARCHIVE_ROOT OR NOT SB_TEST_ROOT)
    message(FATAL_ERROR "SB_ARCHIVE_ROOT and SB_TEST_ROOT are required")
endif()
file(GLOB SB_ARCHIVES "${SB_ARCHIVE_ROOT}/SecondBrain-*.tar.gz" "${SB_ARCHIVE_ROOT}/SecondBrain-*.zip")
list(LENGTH SB_ARCHIVES SB_ARCHIVE_COUNT)
if(NOT SB_ARCHIVE_COUNT EQUAL 1)
    message(FATAL_ERROR "Expected one application archive, found ${SB_ARCHIVE_COUNT}")
endif()
list(GET SB_ARCHIVES 0 SB_ARCHIVE)
get_filename_component(SB_ARCHIVE "${SB_ARCHIVE}" ABSOLUTE)
get_filename_component(SB_TEST_ROOT "${SB_TEST_ROOT}" ABSOLUTE)
set(SB_UNPACK "${SB_TEST_ROOT}/Paket ü")
file(MAKE_DIRECTORY "${SB_UNPACK}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${SB_ARCHIVE}"
    WORKING_DIRECTORY "${SB_UNPACK}" RESULT_VARIABLE SB_UNPACK_RESULT)
if(NOT SB_UNPACK_RESULT EQUAL 0)
    message(FATAL_ERROR "Archive could not be extracted")
endif()
file(GLOB SB_ROOTS LIST_DIRECTORIES TRUE "${SB_UNPACK}/SecondBrain-*")
list(LENGTH SB_ROOTS SB_ROOT_COUNT)
if(NOT SB_ROOT_COUNT EQUAL 1)
    message(FATAL_ERROR "Expected one package directory")
endif()
list(GET SB_ROOTS 0 SB_ROOT)
if(APPLE)
    set(SB_EXECUTABLE "${SB_ROOT}/secondbrain.app/Contents/MacOS/secondbrain")
    set(SB_ASSETS "${SB_ROOT}/secondbrain.app/Contents/Resources/assets")
elseif(WIN32)
    set(SB_EXECUTABLE "${SB_ROOT}/secondbrain.exe")
    set(SB_ASSETS "${SB_ROOT}/assets")
else()
    set(SB_EXECUTABLE "${SB_ROOT}/secondbrain")
    set(SB_ASSETS "${SB_ROOT}/assets")
endif()
foreach(SB_RESOURCE IN ITEMS "${SB_EXECUTABLE}" "${SB_ASSETS}/fonts/NotoSans-Regular.ttf"
    "${SB_ASSETS}/fonts/NotoSansMono-Regular.ttf" "${SB_ROOT}/licenses/SDL3.txt"
    "${SB_ROOT}/licenses/Nuklear.txt" "${SB_ROOT}/licenses/Noto.txt" "${SB_ROOT}/QUICKSTART.txt")
    if(NOT EXISTS "${SB_RESOURCE}")
        message(FATAL_ERROR "Missing package resource: ${SB_RESOURCE}")
    endif()
endforeach()
# Run the extracted app with its bundled assets from a different directory.
execute_process(COMMAND "${SB_EXECUTABLE}" --self-test "${SB_TEST_ROOT}/Bedienprüfung ü"
    WORKING_DIRECTORY "${SB_UNPACK}" RESULT_VARIABLE SB_RESULT
    OUTPUT_VARIABLE SB_OUTPUT ERROR_VARIABLE SB_ERROR TIMEOUT 240)
message(STATUS "${SB_OUTPUT}")
if(NOT SB_RESULT EQUAL 0)
    message(FATAL_ERROR "Relocated application failed: ${SB_RESULT}\n${SB_ERROR}")
endif()
message(STATUS "Extracted package passed the desktop workflow: ${SB_ARCHIVE}")

execute_process(COMMAND "${SB_EXECUTABLE}" --keyboard-test "${SB_TEST_ROOT}/Tastaturprüfung ü"
    WORKING_DIRECTORY "${SB_UNPACK}" RESULT_VARIABLE SB_KEYBOARD_RESULT
    OUTPUT_VARIABLE SB_KEYBOARD_OUTPUT ERROR_VARIABLE SB_KEYBOARD_ERROR TIMEOUT 300)
message(STATUS "${SB_KEYBOARD_OUTPUT}")
if(NOT SB_KEYBOARD_RESULT EQUAL 0)
    message(FATAL_ERROR "Relocated keyboard workflow failed: ${SB_KEYBOARD_RESULT}\n${SB_KEYBOARD_ERROR}")
endif()
message(STATUS "Extracted package passed the keyboard-only workflow")
