#ifndef SB_ICONS_H
#define SB_ICONS_H
#include "ui.h"
typedef enum { SB_ICON_NONE, SB_ICON_CLOSE, SB_ICON_ADD, SB_ICON_MINUS, SB_ICON_LEFT, SB_ICON_RIGHT, SB_ICON_HOME, SB_ICON_EXPAND, SB_ICON_COLLAPSE, SB_ICON_LIST, SB_ICON_NOTE, SB_ICON_PROJECT, SB_ICON_EDIT, SB_ICON_SAVE, SB_ICON_ARCHIVE, SB_ICON_COPY, SB_ICON_FILTER, SB_ICON_RELOAD, SB_ICON_EYE, SB_ICON_ACTIONS, SB_ICON_SEARCH, SB_ICON_SETTINGS, SB_ICON_HELP, SB_ICON_LINK, SB_ICON_CONTEXT, SB_ICON_PALETTE, SB_ICON_MOTION, SB_ICON_FONT, SB_ICON_GLASS, SB_ICON_COUNT } SBIcon;
SBIcon sb_icon_for(const char *id);
void sb_icon_draw(struct nk_command_buffer *canvas, SBIcon icon, struct nk_rect bounds, struct nk_color color);
#endif
