cmake_minimum_required(VERSION 3.20)
if(NOT SB_BUILD_DIR)
    message(FATAL_ERROR "SB_BUILD_DIR is required")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${SB_BUILD_DIR}" --config "${SB_BUILD_CONFIG}" --parallel 4
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
message("${output}${errors}")
if(NOT result EQUAL 0)
    # GitHub truncates individual annotation messages; retain each stream's tail.
    foreach(stream errors output)
        set(diagnostic "${${stream}}")
        string(LENGTH "${diagnostic}" length)
        if(length GREATER 3500)
            math(EXPR start "${length}-3500")
            string(SUBSTRING "${diagnostic}" ${start} -1 diagnostic)
        endif()
        string(REPLACE "%" "%25" diagnostic "${diagnostic}")
        string(REPLACE "\r" "%0D" diagnostic "${diagnostic}")
        string(REPLACE "\n" "%0A" diagnostic "${diagnostic}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "::error title=Native build failed (${stream})::${diagnostic}")
    endforeach()
    message(FATAL_ERROR "Build returned ${result}")
endif()
