cmake_minimum_required(VERSION 3.20)
if(NOT SB_TAG MATCHES "^v0\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
    message(FATAL_ERROR "Automatic publication accepts only v0.MINOR.PATCH; 1.0 requires explicit user authorization")
endif()
if(NOT SB_SOURCE_ROOT)
    get_filename_component(SB_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
file(READ "${SB_SOURCE_ROOT}/CMakeLists.txt" SB_CMAKE)
string(REGEX MATCH "project\\(SecondBrain VERSION ([0-9]+\\.[0-9]+\\.[0-9]+) LANGUAGES C\\)" SB_MATCH "${SB_CMAKE}")
if(NOT SB_MATCH OR NOT SB_TAG STREQUAL "v${CMAKE_MATCH_1}")
    message(FATAL_ERROR "Tag and declared application version differ")
endif()
message(STATUS "Verified development tag ${SB_TAG}")
