cmake_minimum_required(VERSION 3.20)
if(NOT SB_TEST_LOG OR NOT EXISTS "${SB_TEST_LOG}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "::notice title=CTest diagnostics::No test log is available")
    return()
endif()
file(READ "${SB_TEST_LOG}" log)
string(REGEX MATCHALL "[0-9]+/[0-9]+ Testing:[^\r\n]*" headings "${log}")
foreach(heading IN LISTS headings)
    string(FIND "${log}" "${heading}" start)
    string(SUBSTRING "${log}" ${start} -1 block)
    string(FIND "${block}" " end time:" finish)
    if(finish GREATER 0)
        string(SUBSTRING "${block}" 0 ${finish} block)
    endif()
    if(block MATCHES "Test Failed")
        string(REGEX MATCHALL "[^\r\n]*(FAIL|failed|Failed|timed out)[^\r\n]*" failures "${block}")
        string(JOIN "\n" summary ${failures})
        string(LENGTH "${block}" length)
        if(length GREATER 2800)
            math(EXPR start "${length}-2800")
            string(SUBSTRING "${block}" ${start} -1 block)
        endif()
        set(block "${heading}\n${summary}\n${block}")
        string(REPLACE "%" "%25" block "${block}")
        string(REPLACE "\r" "%0D" block "${block}")
        string(REPLACE "\n" "%0A" block "${block}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "::error title=CTest failed::${block}")
    endif()
endforeach()
