cmake_minimum_required(VERSION 3.20)
if(NOT SB_DIAGNOSTIC_LOG OR NOT EXISTS "${SB_DIAGNOSTIC_LOG}")
    return()
endif()
file(READ "${SB_DIAGNOSTIC_LOG}" detail)
string(LENGTH "${detail}" length)
if(length GREATER 3500)
    math(EXPR start "${length}-3500")
    string(SUBSTRING "${detail}" ${start} -1 detail)
endif()
string(REPLACE "%" "%25" detail "${detail}")
string(REPLACE "\r" "%0D" detail "${detail}")
string(REPLACE "\n" "%0A" detail "${detail}")
if(NOT SB_DIAGNOSTIC_TITLE)
    set(SB_DIAGNOSTIC_TITLE "UI configure entry")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "::error title=${SB_DIAGNOSTIC_TITLE}::${detail}")
