cmake_minimum_required(VERSION 3.20)
if(NOT SB_DIAGNOSTIC_LOG OR NOT EXISTS "${SB_DIAGNOSTIC_LOG}")
    return()
endif()
file(READ "${SB_DIAGNOSTIC_LOG}" detail)
string(REGEX MATCHALL "[^\r\n]*(FAIL:|ERROR:|AssertionError|ValueError|FileNotFoundError|UnicodeDecodeError)[^\r\n]*" failure_lines "${detail}")
string(JOIN "\n" failure_summary ${failure_lines})
string(LENGTH "${failure_summary}" summary_length)
if(summary_length GREATER 3000)
    string(SUBSTRING "${failure_summary}" 0 3000 failure_summary)
endif()
string(LENGTH "${detail}" length)
if(length GREATER 3500)
    math(EXPR start "${length}-3500")
    string(SUBSTRING "${detail}" ${start} -1 detail)
endif()
set(detail "${failure_summary}\n${detail}")
string(REPLACE "%" "%25" detail "${detail}")
string(REPLACE "\r" "%0D" detail "${detail}")
string(REPLACE "\n" "%0A" detail "${detail}")
if(NOT SB_DIAGNOSTIC_TITLE)
    set(SB_DIAGNOSTIC_TITLE "UI configure entry")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "::error title=${SB_DIAGNOSTIC_TITLE}::${detail}")
