#!/usr/bin/env python3
"""Generate own C word classes from pinned Unicode 18.0.0 inputs."""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'third_party/unicode/18.0.0'
PINNED = {'WordBreakProperty.txt': '8dbfa17063e11084201f33c3e76d485d3b9166930c71db8e39ed1c9234171aec', 'WordBreakTest.txt': '3dd70c071781276067c680d87303f60434adce7b067bd063194af374edad86a5', 'emoji-data.txt': '80d00f8e616a0ef27fd6b8de3b758c06383b5d917e2977709578e68baf733bf1', 'DerivedGeneralCategory.txt': 'd6b151d2d40ee9b1876d26f417980f45ffae47b6055ccf7203cb31f07a030f94'}
CLASSES = {'CR': 1, 'LF': 2, 'Newline': 3, 'Extend': 4, 'ZWJ': 5,
           'Regional_Indicator': 6, 'Format': 7, 'Katakana': 8,
           'Hebrew_Letter': 9, 'ALetter': 10, 'Single_Quote': 11,
           'Double_Quote': 12, 'MidNumLet': 13, 'MidLetter': 14,
           'MidNum': 15, 'ExtendNumLet': 16, 'WSegSpace': 17, 'Numeric': 18}

def ranges(filename, mode):
    data = (DATA / filename).read_bytes()
    if hashlib.sha256(data).hexdigest() != PINNED[filename]:
        raise ValueError('Unicode word input differs from its pinned source: ' + filename)
    values = []
    for line in data.decode('utf-8').splitlines():
        fields = [x.strip() for x in line.split('#', 1)[0].split(';')]
        if len(fields) < 2:
            continue
        span, prop = fields[:2]
        if mode == 'word':
            value = CLASSES[prop]
        elif mode == 'emoji':
            if prop != 'Extended_Pictographic':
                continue
            value = 1
        else:
            if prop[0] not in 'LN':
                continue
            value = 1
        ends = [int(x, 16) for x in span.split('..')]
        values.append((ends[0], ends[-1], value))
    merged = []
    for lo, hi, value in sorted(values):
        if merged and lo <= merged[-1][1]:
            raise ValueError('Overlapping Unicode word ranges')
        if merged and merged[-1][1] + 1 == lo and merged[-1][2] == value:
            merged[-1] = (merged[-1][0], hi, value)
        else:
            merged.append((lo, hi, value))
    return merged

def generate():
    for filename, digest in PINNED.items():
        if hashlib.sha256((DATA / filename).read_bytes()).hexdigest() != digest:
            raise ValueError('Pinned Unicode source changed: ' + filename)
    out = ['/* Unicode 18.0.0; generated by tools/make_word_data.py.',
           '   Copyright Unicode, Inc.; Unicode License v3: third_party/licenses/Unicode.txt. */']
    for name, filename, mode in [('word_classes', 'WordBreakProperty.txt', 'word'),
                                 ('word_emoji', 'emoji-data.txt', 'emoji'),
                                 ('word_letters_numbers', 'DerivedGeneralCategory.txt', 'category')]:
        out += [f'/* {filename} SHA-256: {PINNED[filename]} */',
                f'static const WordRange {name}[]={{']
        out += [f'    {{0x{lo:X},0x{hi:X},{value}}},' for lo, hi, value in ranges(filename, mode)]
        out.append('};')
    return '\n'.join(out) + '\n'

if __name__ == '__main__':
    (ROOT / 'src/word_data.inc').write_text(generate(), encoding='utf-8')
