#!/usr/bin/env python3
"""Generate the own C grapheme property tables from pinned Unicode 18.0 data."""
from pathlib import Path
import hashlib
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'third_party/unicode/18.0.0'
PINNED = {'GraphemeBreakProperty.txt': '0839dcb79e4ac639ecd538b1abf7c9d22e3f9dd265b7e182d33627aa4d75b45a', 'DerivedCoreProperties.txt': '09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9', 'emoji-data.txt': '80d00f8e616a0ef27fd6b8de3b758c06383b5d917e2977709578e68baf733bf1', 'GraphemeBreakTest.txt': 'b0cf047ee94485bbdc846de2b902f5f8a815f6b674f9d04223cddadd91c9df31'}

GCB = {'CR': 1, 'LF': 2, 'Control': 3, 'Extend': 4, 'ZWJ': 5,
       'Regional_Indicator': 6, 'Prepend': 7, 'SpacingMark': 8,
       'L': 9, 'V': 10, 'T': 11, 'LV': 12, 'LVT': 13}

def ranges(filename, mode):
    if hashlib.sha256((DATA / filename).read_bytes()).hexdigest() != PINNED[filename]:
        raise ValueError('Unicode input differs from the pinned source: ' + filename)
    values = []
    for line in (DATA / filename).read_text(encoding='utf-8').splitlines():
        fields = line.split('#', 1)[0].strip().split(';')
        if len(fields) < 2:
            continue
        span, prop = (x.strip() for x in fields[:2])
        if mode == 'gcb':
            value = GCB[prop]
        elif mode == 'incb':
            if prop != 'InCB':
                continue
            value = {'Consonant': 1, 'Extend': 2, 'Linker': 3}[fields[2].strip()]
        else:
            if prop != 'Extended_Pictographic':
                continue
            value = 1
        if not re.fullmatch(r'[0-9A-F]+(?:\.\.[0-9A-F]+)?', span):
            raise ValueError(span)
        ends = [int(x, 16) for x in span.split('..')]
        values.append((ends[0], ends[-1], value))
    merged = []
    for lo, hi, value in sorted(values):
        if merged and lo <= merged[-1][1]:
            raise ValueError('Overlapping Unicode property ranges')
        if merged and merged[-1][1] + 1 == lo and merged[-1][2] == value:
            merged[-1] = (merged[-1][0], hi, value)
        else:
            merged.append((lo, hi, value))
    return merged

def generate():
    out = ['/* Generated by tools/make_grapheme_data.py. Unicode 18.0.0 data.\n'
           '   Copyright Unicode, Inc.; Unicode License v3: third_party/licenses/Unicode.txt. */']
    for name, filename, mode in [('gcb', 'GraphemeBreakProperty.txt', 'gcb'),
                                 ('incb', 'DerivedCoreProperties.txt', 'incb'),
                                 ('pictographic', 'emoji-data.txt', 'emoji')]:
        digest = hashlib.sha256((DATA / filename).read_bytes()).hexdigest()
        out.append(f'/* {filename} SHA-256: {digest} */')
        out.append(f'static const Range {name}[]={{')
        out.extend(f'    {{0x{lo:X},0x{hi:X},{value}}},' for lo, hi, value in ranges(filename, mode))
        out.append('};')
    return '\n'.join(out) + '\n'

if __name__ == '__main__':
    (ROOT / 'src/grapheme_data.inc').write_text(generate(), encoding='utf-8')
