#!/usr/bin/env python3
"""Create C UI script/pairing properties from byte-checked Unicode 18 sources."""
from pathlib import Path
import hashlib
import json
import argparse

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'third_party/unicode/18.0.0'
PINS = {
    'Scripts.txt': '0071fd81b6aeae25f6e8bce8efec3066a6476a91b49bdb2f52dc76e817862a6a',
    'ScriptExtensions.txt': '5c9d34a922f687726f2a8bcf57d49f905987e51f1b21b58c95a00fbe255cec23',
    'PropertyValueAliases.txt': '06c4c8eaf7b0bf34abe73b113da1215bd784ac254d4c223600b90267caa4bbbd',
    'BidiBrackets.txt': '4b3b62e4a14b84ee752808c810c602534921c09a4a1bf78cfbee566d66c125b3',
}
def records(name):
    path = DATA / name
    if hashlib.sha256(path.read_bytes()).hexdigest() != PINS[name]:
        raise ValueError('Unreviewed Unicode script source: ' + name)
    for line in path.read_text().splitlines():
        fields = [s.strip() for s in line.split('#', 1)[0].split(';')]
        if len(fields) > 1:
            yield fields

def tag(name):
    if len(name) != 4 or not name.isascii() or not name.isalpha():
        raise ValueError(name)
    return int.from_bytes(name.encode('ascii'), 'big')

def span(text):
    ends = [int(s, 16) for s in text.split('..')]
    if not 0 <= ends[0] <= ends[-1] <= 0x10ffff:
        raise ValueError(text)
    return ends[0], ends[-1]

def generate():
    aliases = {}
    for fields in records('PropertyValueAliases.txt'):
        if fields[0] == 'sc':
            for name in fields[1:]:
                aliases[name] = tag(fields[1])
    properties = sorted((*span(f[0]), aliases[f[1]]) for f in records('Scripts.txt'))
    merged = []
    for lo, hi, value in properties:
        if merged and lo <= merged[-1][1]:
            raise ValueError('Overlapping scripts')
        if merged and lo == merged[-1][1]+1 and value == merged[-1][2]:
            merged[-1] = merged[-1][0], hi, value
        else:
            merged.append((lo, hi, value))
    extensions, values, sets = [], [], {}
    for fields in records('ScriptExtensions.txt'):
        members = tuple(sorted({aliases[n] for n in fields[1].split()}))
        if not members or len(members) != len(fields[1].split()):
            raise ValueError('Empty or duplicate Script_Extensions')
        if members not in sets:
            sets[members] = len(values)
            values.extend(members)
        extensions.append((*span(fields[0]), sets[members], len(members)))
    for before, after in zip(extensions, extensions[1:]):
        if before[1] >= after[0]:
            raise ValueError('Overlapping extensions')
    brackets = [(int(f[0], 16), int(f[1], 16), {'o': 1, 'c': 2}[f[2]]) for f in records('BidiBrackets.txt')]
    out = ['/* Generated by tools/make_script_data.py; Unicode 18.0.0.',
           '   Unicode License V3: third_party/licenses/Unicode.txt. */']
    out += [f'/* {n} SHA-256 {h} */' for n, h in PINS.items()]
    out += ['static const ScriptRange script_ranges[]={']
    out += [f'{{0x{lo:X},0x{hi:X},0x{t:08X}}},' for lo, hi, t in merged]
    out += ['};', 'static const uint32_t script_extensions[]={']
    out += [f'0x{v:08X},' for v in values]
    out += ['};', 'static const ExtensionRange extension_ranges[]={']
    out += [f'{{0x{lo:X},0x{hi:X},{start},{count}}},' for lo, hi, start, count in extensions]
    out += ['};', 'static const ScriptBracket script_brackets[]={']
    out += [f'{{0x{cp:X},0x{pair:X},{kind}}},' for cp, pair, kind in brackets]
    out += ['};']
    return '\n'.join(out)+'\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'app/script_data.inc'
    rendered = generate()
    if args.check:
        if output.read_bytes() != rendered.encode():
            raise ValueError('Generated script table differs')
    else:
        output.write_text(rendered)
    print(hashlib.sha256(rendered.encode()).hexdigest())
