#!/usr/bin/env python3
"""Generate own C character classes for CommonMark delimiter rules."""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'third_party/unicode/18.0.0/DerivedGeneralCategory.txt'
SHA256 = 'd6b151d2d40ee9b1876d26f417980f45ffae47b6055ccf7203cb31f07a030f94'

def generate():
    data = SOURCE.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256:
        raise ValueError('Unicode character classes differ from the pinned source')
    ranges = []
    for line in data.decode('utf-8').splitlines():
        fields = line.split('#', 1)[0].strip().split(';')
        if len(fields) != 2:
            continue
        span, category = (s.strip() for s in fields)
        if category[0] not in 'PS':
            continue
        ends = [int(s, 16) for s in span.split('..')]
        ranges.append((ends[0], ends[-1]))
    merged = []
    for lo, hi in sorted(ranges):
        if merged and lo <= merged[-1][1]:
            raise ValueError('Overlapping character ranges')
        if merged and lo == merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], hi)
        else:
            merged.append((lo, hi))
    lines = ['/* Unicode 18.0.0; generated by tools/make_inline_unicode.py.',
             '   Unicode, Inc.; Unicode License v3: third_party/licenses/Unicode.txt.',
             '   DerivedGeneralCategory.txt SHA-256: ' + SHA256 + ' */',
             'static const UClassRange unicode_punctuation[]={']
    lines.extend(f'    {{0x{lo:X},0x{hi:X}}},' for lo, hi in merged)
    return '\n'.join(lines + ['};', ''])

if __name__ == '__main__':
    (ROOT / 'src/inline_unicode.inc').write_text(generate(), encoding='utf-8')
