#!/usr/bin/env python3
"""Generate the own C full/default case-fold table from pinned Unicode data."""
from pathlib import Path
import hashlib
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'third_party/unicode/18.0.0/CaseFolding.txt'
SHA256 = 'a004797658a457bec4dc11683e39f69249ea3b595b752dbea6721c4c9f587b0d'
def generate():
    data = SOURCE.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256:
        raise ValueError('Case-fold source differs from its pinned hash')
    mappings = {}
    for line in data.decode('utf-8').splitlines():
        fields = [p.strip() for p in line.split('#', 1)[0].split(';')]
        if len(fields) < 3 or fields[1] not in ('C', 'F'):
            continue
        cp = int(fields[0], 16)
        target = [int(p, 16) for p in fields[2].split()]
        if cp in mappings or not 1 <= len(target) <= 3:
            raise ValueError('Unexpected case-fold mapping')
        mappings[cp] = target
    lines = ['/* Unicode 18.0.0 C/F mappings, Unicode License V3; generated by tools/make_casefold_data.py. */', 'static const CaseFold case_folds[] = {']
    for cp, target in sorted(mappings.items()):
        padded = target + [0] * (3 - len(target))
        lines.append('    {0x%x, %d, {0x%x, 0x%x, 0x%x}},' % (cp, len(target), *padded))
    lines.append('};')
    return '\n'.join(lines) + '\n'
if __name__ == '__main__':
    (ROOT / 'src/casefold_data.inc').write_text(generate(), encoding='utf-8')
