cmake_minimum_required(VERSION 3.20)
if(NOT SB_PACKAGE_ROOT OR NOT SB_OUTPUT)
    message(FATAL_ERROR "SB_PACKAGE_ROOT and SB_OUTPUT are required")
endif()
if(SB_RUNTIME_TOOL)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${SB_RUNTIME_TOOL}")
endif()
set(excluded "")
if(APPLE)
    set(app "${SB_PACKAGE_ROOT}/secondbrain.app/Contents/MacOS/secondbrain")
    set(cli "${SB_PACKAGE_ROOT}/secondbrain-cli")
    # Current macOS stores these libraries in the dyld shared cache.
    set(excluded "^/System/Library/" "^/usr/lib/")
elseif(WIN32)
    set(app "${SB_PACKAGE_ROOT}/secondbrain.exe")
    set(cli "${SB_PACKAGE_ROOT}/secondbrain-cli.exe")
    # API sets are OS loader contracts, not package files.
    set(excluded "^api-ms-" "^ext-ms-")
else()
    set(app "${SB_PACKAGE_ROOT}/secondbrain")
    set(cli "${SB_PACKAGE_ROOT}/secondbrain-cli")
endif()
foreach(binary IN ITEMS "${app}" "${cli}")
    if(NOT EXISTS "${binary}")
        message(FATAL_ERROR "Package program missing: ${binary}")
    endif()
endforeach()
if(NOT SB_RUNTIME_BINARY OR (NOT SB_RUNTIME_BINARY STREQUAL app AND NOT SB_RUNTIME_BINARY STREQUAL cli))
    message(FATAL_ERROR "SB_RUNTIME_BINARY must identify a package program")
endif()
file(GET_RUNTIME_DEPENDENCIES EXECUTABLES "${SB_RUNTIME_BINARY}"
    RESOLVED_DEPENDENCIES_VAR resolved UNRESOLVED_DEPENDENCIES_VAR unresolved
    CONFLICTING_DEPENDENCIES_PREFIX conflict PRE_EXCLUDE_REGEXES ${excluded})

function(json_array output)
    set(result "[")
    set(separator "")
    foreach(value IN LISTS ARGN)
        string(REPLACE "\\" "\\\\" value "${value}")
        string(REPLACE "\"" "\\\"" value "${value}")
        string(REPLACE "\n" "\\n" value "${value}")
        string(REPLACE "\r" "\\r" value "${value}")
        string(REPLACE "\t" "\\t" value "${value}")
        string(APPEND result "${separator}\"${value}\"")
        set(separator ",")
    endforeach()
    string(APPEND result "]")
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
json_array(resolved_json ${resolved})
json_array(unresolved_json ${unresolved})
json_array(conflict_json ${conflict_FILENAMES})
json_array(excluded_json ${excluded})
file(WRITE "${SB_OUTPUT}" "{\"resolved\":${resolved_json},\"unresolved\":${unresolved_json},\"conflicts\":${conflict_json},\"excluded_os_contract_patterns\":${excluded_json}}\n")
