cmake_minimum_required(VERSION 3.20)
if(NOT SB_VERSION MATCHES "^0\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$" OR NOT IS_DIRECTORY "${SB_ASSET_DIR}")
    message(FATAL_ERROR "Development version and asset directory required")
endif()
file(GLOB SB_ARCHIVES "${SB_ASSET_DIR}/*.zip" "${SB_ASSET_DIR}/*.tar.gz")
list(LENGTH SB_ARCHIVES SB_COUNT)
if(NOT SB_COUNT EQUAL 4)
    message(FATAL_ERROR "Expected exactly four verified platform archives")
endif()
foreach(SB_PLATFORM IN ITEMS Windows Darwin Linux)
    if(SB_PLATFORM STREQUAL "Windows")
        set(SB_EXT zip)
    else()
        set(SB_EXT tar.gz)
    endif()
    file(GLOB SB_PLATFORM_FILES "${SB_ASSET_DIR}/SecondBrain-${SB_VERSION}-${SB_PLATFORM}-*.${SB_EXT}")
    list(LENGTH SB_PLATFORM_FILES SB_PLATFORM_COUNT)
    if(SB_PLATFORM STREQUAL "Darwin")
        set(SB_EXPECTED_COUNT 2)
    else()
        set(SB_EXPECTED_COUNT 1)
    endif()
    if(NOT SB_PLATFORM_COUNT EQUAL SB_EXPECTED_COUNT)
        message(FATAL_ERROR "Missing or duplicate ${SB_PLATFORM} archive for ${SB_VERSION}")
    endif()
endforeach()
foreach(SB_MAC_ARCH IN ITEMS arm64 x86_64)
    if(NOT EXISTS "${SB_ASSET_DIR}/SecondBrain-${SB_VERSION}-Darwin-${SB_MAC_ARCH}.tar.gz")
        message(FATAL_ERROR "Missing ${SB_MAC_ARCH} macOS archive")
    endif()
endforeach()
list(SORT SB_ARCHIVES)
set(SB_SUMS "")
foreach(SB_FILE IN LISTS SB_ARCHIVES)
    get_filename_component(SB_NAME "${SB_FILE}" NAME)
    if(IS_DIRECTORY "${SB_FILE}" OR IS_SYMLINK "${SB_FILE}" OR NOT SB_NAME MATCHES "^[A-Za-z0-9_.-]+$")
        message(FATAL_ERROR "Invalid release asset")
    endif()
    file(SHA256 "${SB_FILE}" SB_HASH)
    string(APPEND SB_SUMS "${SB_HASH}  ${SB_NAME}\n")
endforeach()
if(SB_VERIFY)
    if(NOT EXISTS "${SB_EXPECTED_SUMS}" OR NOT EXISTS "${SB_ASSET_DIR}/SHA256SUMS")
        message(FATAL_ERROR "Expected and downloaded checksum manifests required")
    endif()
    file(READ "${SB_EXPECTED_SUMS}" SB_EXPECTED)
    file(READ "${SB_ASSET_DIR}/SHA256SUMS" SB_DOWNLOADED)
    if(NOT SB_SUMS STREQUAL SB_EXPECTED OR NOT SB_DOWNLOADED STREQUAL SB_EXPECTED)
        message(FATAL_ERROR "Downloaded release bytes differ from verified packages")
    endif()
else()
    if(EXISTS "${SB_ASSET_DIR}/SHA256SUMS")
        message(FATAL_ERROR "Existing checksum manifest will not be overwritten")
    endif()
    file(WRITE "${SB_ASSET_DIR}/SHA256SUMS" "${SB_SUMS}")
endif()
message(STATUS "Release asset hashes verified for ${SB_VERSION}")
