cmake_minimum_required(VERSION 3.20)
get_filename_component(cmake_bin "${CMAKE_COMMAND}" DIRECTORY)
find_program(ctest_executable ctest HINTS "${cmake_bin}" REQUIRED)
execute_process(COMMAND "${ctest_executable}" --test-dir "${SB_TEST_DIR}" -C "${SB_TEST_CONFIG}" --output-on-failure
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
message("${output}${errors}")
if(IS_DIRECTORY "${SB_TEST_DIR}")
    file(WRITE "${SB_TEST_DIR}/checked-ctest.log" "${output}${errors}")
endif()
if(NOT result EQUAL 0)
    set(log "${output}${errors}")
    string(REGEX MATCHALL "[^\r\n]*(FAIL|failed|Failed|timed out|Error)[^\r\n]*" failures "${log}")
    string(JOIN "\n" summary ${failures})
    string(LENGTH "${log}" length)
    if(length GREATER 1800)
        math(EXPR start "${length}-1800")
        string(SUBSTRING "${log}" ${start} -1 log)
    endif()
    set(log "CTest returned ${result}\n${summary}\n${log}")
    string(REPLACE "%" "%25" log "${log}")
    string(REPLACE "\r" "%0D" log "${log}")
    string(REPLACE "\n" "%0A" log "${log}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "::error title=CTest command failed::${log}")
    message(FATAL_ERROR "CTest returned ${result}")
endif()
