cmake_minimum_required(VERSION 3.20)
set(bus "${SB_UNIX_SOURCE}/src/atspi/bus.rs")
file(SHA256 "${bus}" bus_hash)
if(bus_hash STREQUAL "ed7f35016b3df2cd2ebcaa2ca8a401e36b3b609c51155d45e8b241c9756acc9d")
    file(READ "${bus}" text)
    string(REPLACE "\"AddAccessible\", &item" "\"AddAccessible\", &(item,)" text "${text}")
    string(REPLACE "\"RemoveAccessible\", &reference" "\"RemoveAccessible\", &(reference,)" text "${text}")
    file(WRITE "${bus}" "${text}")
elseif(NOT bus_hash STREQUAL "52ff001b67b5121afe964bb745132ece5648ae367744cec0a87edd12281ffdf8")
    message(FATAL_ERROR "Unrecognized AccessKit Unix cache source; refusing an unverified patch")
endif()
set(node_source "${SB_ATSPI_SOURCE}/src/node.rs")
file(SHA256 "${node_source}" node_hash)
if(node_hash STREQUAL "8fafcc4f13a061cc46ea070a7b4e240027487f8f5507d75c449253c95136e4cf")
    file(READ "${node_source}" node_text)
    string(REPLACE "        let mut attributes = HashMap::new();\n        if let Some(placeholder) = self.placeholder() {"
        "        let mut attributes = HashMap::new();\n        if let Some(level) = self.0.level().and_then(|level| level.checked_add(1)) {\n            attributes.insert(\"level\", level.to_string());\n        }\n        if let Some(placeholder) = self.placeholder() {" node_text "${node_text}")
    file(WRITE "${node_source}" "${node_text}")
elseif(NOT node_hash STREQUAL "32f8e038ed152668c190a3acd672485b60e0e9c9abd017fc746bf3d502c47dd1")
    message(FATAL_ERROR "Unrecognized AccessKit AT-SPI level source; refusing an unverified patch")
endif()
file(READ "${SB_C_SOURCE}/Cargo.toml" manifest)
string(FIND "${manifest}" "[patch.crates-io]" patch_section)
if(patch_section LESS 0)
    file(RELATIVE_PATH relative "${SB_C_SOURCE}" "${SB_UNIX_SOURCE}")
    string(REPLACE "\\" "\\\\" relative "${relative}")
    string(REPLACE "\"" "\\\"" relative "${relative}")
    file(APPEND "${SB_C_SOURCE}/Cargo.toml" "\n[patch.crates-io]\naccesskit_unix = { path = \"${relative}\" }\n")
endif()
file(READ "${SB_C_SOURCE}/Cargo.toml" manifest)
string(FIND "${manifest}" "accesskit_atspi_common = { path =" common_patch)
if(common_patch LESS 0)
    file(RELATIVE_PATH common_relative "${SB_C_SOURCE}" "${SB_ATSPI_SOURCE}")
    string(REPLACE "\\" "\\\\" common_relative "${common_relative}")
    string(REPLACE "\"" "\\\"" common_relative "${common_relative}")
    file(APPEND "${SB_C_SOURCE}/Cargo.toml" "accesskit_atspi_common = { path = \"${common_relative}\" }\n")
endif()
# Same dependency version and graph; only its verified source becomes the local UI patch.
file(READ "${SB_C_SOURCE}/Cargo.lock" lock)
string(REPLACE "name = \"accesskit_unix\"\nversion = \"0.24.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"202f24df034a7476d07b7f74284de84f6d62aabd858dbe7ee9cad3b7ad6f8f9d\"\n"
    "name = \"accesskit_unix\"\nversion = \"0.24.0\"\n" lock "${lock}")
file(WRITE "${SB_C_SOURCE}/Cargo.lock" "${lock}")

file(READ "${SB_C_SOURCE}/Cargo.lock" common_lock)
string(REPLACE "name = \"accesskit_atspi_common\"\nversion = \"0.21.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"52c182f9c282ac9c5638d876d551d15e5f7d397ec263349a0c6a2b61595dd5e4\"\n"
    "name = \"accesskit_atspi_common\"\nversion = \"0.21.0\"\n" common_lock "${common_lock}")
file(WRITE "${SB_C_SOURCE}/Cargo.lock" "${common_lock}")
