# Hash-checked UI extension and empty-bitmap correction. No domain linkage.
set(SB_TTF_SOURCE "${sb_sdl_ttf_SOURCE_DIR}/src/SDL_ttf.c")
set(SB_TTF_ORIGINAL_SHA "25a42804b18809e5c4b2eb8ed787701551d0c680aff774b7d8c54486c0d42d38")
set(SB_TTF_FIXED_SHA "effab05fe248deadc02a1259ca640fa9c785909c3398ae16b13a1fabbe9c1b9e")
set(SB_TTF_SHAPE_MARKER "\n/* SecondBrain contextual glyph positions, UI only. */\n#include \"ttf_shape.inc\"\n")
file(READ "${SB_TTF_SOURCE}" SB_TTF_TEXT)
string(SHA256 SB_TTF_SHA "${SB_TTF_TEXT}")
if(SB_TTF_SHA STREQUAL SB_TTF_ORIGINAL_SHA)
    set(SB_TTF_BODY "${SB_TTF_TEXT}")
else()
    string(LENGTH "${SB_TTF_SHAPE_MARKER}" SB_TTF_MARKER_LENGTH)
    string(LENGTH "${SB_TTF_TEXT}" SB_TTF_LENGTH)
    math(EXPR SB_TTF_BODY_LENGTH "${SB_TTF_LENGTH}-${SB_TTF_MARKER_LENGTH}")
    if(SB_TTF_BODY_LENGTH LESS 1)
        message(FATAL_ERROR "Unrecognized SDL_ttf shape source")
    endif()
    string(SUBSTRING "${SB_TTF_TEXT}" ${SB_TTF_BODY_LENGTH} -1 SB_TTF_SUFFIX)
    string(SUBSTRING "${SB_TTF_TEXT}" 0 ${SB_TTF_BODY_LENGTH} SB_TTF_BODY)
    string(SHA256 SB_TTF_BODY_SHA "${SB_TTF_BODY}")
    if(NOT SB_TTF_SUFFIX STREQUAL SB_TTF_SHAPE_MARKER OR
       (NOT SB_TTF_BODY_SHA STREQUAL SB_TTF_ORIGINAL_SHA AND NOT SB_TTF_BODY_SHA STREQUAL SB_TTF_FIXED_SHA))
        message(FATAL_ERROR "Unrecognized SDL_ttf source; refusing an unverified extension")
    endif()
endif()
string(SHA256 SB_TTF_BODY_SHA "${SB_TTF_BODY}")
if(SB_TTF_BODY_SHA STREQUAL SB_TTF_ORIGINAL_SHA)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/../third_party/ui/ttf_empty_glyph_guard.inc" SB_TTF_EMPTY_GUARD)
    string(REPLACE "            Uint8 *saved_buffer = image->buffer;"
        "${SB_TTF_EMPTY_GUARD}            Uint8 *saved_buffer = image->buffer;"
        SB_TTF_BODY "${SB_TTF_BODY}")
    string(SHA256 SB_TTF_BODY_SHA "${SB_TTF_BODY}")
    if(NOT SB_TTF_BODY_SHA STREQUAL SB_TTF_FIXED_SHA)
        message(FATAL_ERROR "Unrecognized SDL_ttf empty-bitmap correction")
    endif()
endif()
set(SB_TTF_PREPARED "${SB_TTF_BODY}${SB_TTF_SHAPE_MARKER}")
if(NOT SB_TTF_TEXT STREQUAL SB_TTF_PREPARED)
    file(CONFIGURE OUTPUT "${SB_TTF_SOURCE}" CONTENT "${SB_TTF_PREPARED}" @ONLY NEWLINE_STYLE UNIX)
endif()
