# Additional native table patterns for the pinned UI adapter. No new crates.
set(node_source "${SB_WINDOWS_SOURCE}/src/node.rs")
file(SHA256 "${node_source}" node_hash)
if(node_hash STREQUAL "160ff7058edfcb84b8651d4f0111e8839cd1e63c2f08bb309ef65c9e028efb67")
    file(READ "${node_source}" node)
    set(interfaces "    IWindowProvider\n)]")
    string(FIND "${node}" "${interfaces}" interfaces_at)
    string(FIND "${node}" "patterns! {" patterns_at)
    if(interfaces_at LESS 0 OR patterns_at LESS 0)
        message(FATAL_ERROR "AccessKit Windows table patch boundaries are missing")
    endif()
    file(READ "${CMAKE_CURRENT_LIST_DIR}/../third_party/ui/accesskit_windows_table_patterns.rs" patterns)
    string(REPLACE "${interfaces}" "    IWindowProvider,\n    IGridProvider,\n    IGridItemProvider,\n    ITableProvider,\n    ITableItemProvider\n)]" node "${node}")
    string(REPLACE "patterns! {" "patterns! {\n${patterns}" node "${node}")
    string(APPEND node "\ninclude!(\"secondbrain_table.rs\");\n")
    file(CONFIGURE OUTPUT "${node_source}" CONTENT "${node}" @ONLY NEWLINE_STYLE UNIX)
elseif(NOT node_hash STREQUAL "3368a6cdfec3e48784404e37604c295a3ba239e8f16e8e358ce24023bebed877")
    message(FATAL_ERROR "Unrecognized AccessKit Windows node source; refusing an unverified table patch")
endif()
file(SHA256 "${node_source}" node_hash)
if(NOT node_hash STREQUAL "3368a6cdfec3e48784404e37604c295a3ba239e8f16e8e358ce24023bebed877")
    message(FATAL_ERROR "Unexpected result of AccessKit Windows table patch: ${node_hash}")
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/../third_party/ui/accesskit_windows_table.rs"
    "${SB_WINDOWS_SOURCE}/src/secondbrain_table.rs" COPYONLY)
