# A narrow, hash-checked extension in the fixed UI library. No domain linkage.
set(SB_TTF_SOURCE "${sb_sdl_ttf_SOURCE_DIR}/src/SDL_ttf.c")
file(SHA256 "${SB_TTF_SOURCE}" SB_TTF_SHA)
set(SB_TTF_SHAPE_MARKER "\n/* SecondBrain contextual glyph positions, UI only. */\n#include \"ttf_shape.inc\"\n")
if(SB_TTF_SHA STREQUAL "25a42804b18809e5c4b2eb8ed787701551d0c680aff774b7d8c54486c0d42d38")
    file(READ "${SB_TTF_SOURCE}" SB_TTF_TEXT)
    string(APPEND SB_TTF_TEXT "${SB_TTF_SHAPE_MARKER}")
    file(CONFIGURE OUTPUT "${SB_TTF_SOURCE}" CONTENT "${SB_TTF_TEXT}" @ONLY NEWLINE_STYLE UNIX)
else()
    file(READ "${SB_TTF_SOURCE}" SB_TTF_TEXT)
    string(LENGTH "${SB_TTF_SHAPE_MARKER}" SB_TTF_MARKER_LENGTH)
    string(LENGTH "${SB_TTF_TEXT}" SB_TTF_LENGTH)
    math(EXPR SB_TTF_ORIGINAL_LENGTH "${SB_TTF_LENGTH}-${SB_TTF_MARKER_LENGTH}")
    if(SB_TTF_ORIGINAL_LENGTH LESS 1)
        message(FATAL_ERROR "Unrecognized SDL_ttf shape source")
    endif()
    string(SUBSTRING "${SB_TTF_TEXT}" ${SB_TTF_ORIGINAL_LENGTH} -1 SB_TTF_SUFFIX)
    string(SUBSTRING "${SB_TTF_TEXT}" 0 ${SB_TTF_ORIGINAL_LENGTH} SB_TTF_ORIGINAL)
    string(SHA256 SB_TTF_ORIGINAL_SHA "${SB_TTF_ORIGINAL}")
    if(NOT SB_TTF_SUFFIX STREQUAL SB_TTF_SHAPE_MARKER OR
       NOT SB_TTF_ORIGINAL_SHA STREQUAL "25a42804b18809e5c4b2eb8ed787701551d0c680aff774b7d8c54486c0d42d38")
        message(FATAL_ERROR "Unrecognized SDL_ttf source; refusing an unverified extension")
    endif()
endif()
