cmake_minimum_required(VERSION 3.20)
set(source "${SB_WINDOWS_SOURCE}/src/text.rs")
file(SHA256 "${source}" source_hash)
if(source_hash STREQUAL "7f2493b559f0b04884e201d897981a3cce47b2c571863d37ffddb1bb695e5c55")
    set(marker "    fn FindText(")
elseif(source_hash STREQUAL "0fd8cba2e66e5edcaed3fa8d35572e530b7a816a1a716703e96867440709bae1" OR
       source_hash STREQUAL "4c9836aa3845b12cdca68c8f7bbad0b1f6ae88d7f4ba10911a2e5881f86f798f")
    set(marker "    // SecondBrain UI integration; MIT, see the repository LICENSE.")
elseif(source_hash STREQUAL "453fcaaa4faf52c87cc8f15fc50d4710540e35bc181bd6ac3daf28613ed7874a")
    set(marker "")
else()
    message(FATAL_ERROR "Unrecognized AccessKit Windows text source; refusing an unverified patch")
endif()
if(marker)
    file(READ "${source}" text)
    string(FIND "${text}" "${marker}" begin)
    string(FIND "${text}" "    fn GetAttributeValue(" end)
    if(begin LESS 0 OR end LESS_EQUAL begin)
        message(FATAL_ERROR "AccessKit FindText method boundaries are missing")
    endif()
    file(READ "${CMAKE_CURRENT_LIST_DIR}/../third_party/ui/accesskit_findtext.rs" replacement)
    string(REGEX REPLACE "[\r\n]+$" "" replacement "${replacement}")
    string(SUBSTRING "${text}" 0 ${begin} prefix)
    string(SUBSTRING "${text}" ${end} -1 suffix)
    file(CONFIGURE OUTPUT "${source}" CONTENT "${prefix}${replacement}\n\n${suffix}" @ONLY NEWLINE_STYLE UNIX)
endif()
file(SHA256 "${source}" patched_hash)
if(NOT patched_hash STREQUAL "453fcaaa4faf52c87cc8f15fc50d4710540e35bc181bd6ac3daf28613ed7874a")
    message(FATAL_ERROR "Unexpected result of the AccessKit Windows text patch: ${patched_hash}")
endif()
file(READ "${SB_C_SOURCE}/Cargo.toml" manifest)
string(FIND "${manifest}" "[patch.crates-io]" section)
if(section LESS 0)
    file(APPEND "${SB_C_SOURCE}/Cargo.toml" "\n[patch.crates-io]\n")
endif()
string(FIND "${manifest}" "accesskit_windows = { path =" patched_manifest)
if(patched_manifest LESS 0)
    file(RELATIVE_PATH relative "${SB_C_SOURCE}" "${SB_WINDOWS_SOURCE}")
    string(REPLACE "\\" "/" relative "${relative}")
    string(REPLACE "\"" "\\\"" relative "${relative}")
    file(APPEND "${SB_C_SOURCE}/Cargo.toml" "accesskit_windows = { path = \"${relative}\" }\n")
endif()
file(READ "${SB_C_SOURCE}/Cargo.lock" lock)
string(REPLACE "name = \"accesskit_windows\"\nversion = \"0.35.1\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"ce63f35d6bdcf59f26b76b3379063f738e6412cef46999cc772d46aa3de35adb\"\n"
    "name = \"accesskit_windows\"\nversion = \"0.35.1\"\n" lock "${lock}")
file(WRITE "${SB_C_SOURCE}/Cargo.lock" "${lock}")
