cmake_minimum_required(VERSION 3.20)
set(bus "${SB_UNIX_SOURCE}/src/atspi/bus.rs")
file(SHA256 "${bus}" bus_hash)
if(bus_hash STREQUAL "ed7f35016b3df2cd2ebcaa2ca8a401e36b3b609c51155d45e8b241c9756acc9d")
    file(READ "${bus}" text)
    string(REPLACE "\"AddAccessible\", &item" "\"AddAccessible\", &(item,)" text "${text}")
    string(REPLACE "\"RemoveAccessible\", &reference" "\"RemoveAccessible\", &(reference,)" text "${text}")
    file(WRITE "${bus}" "${text}")
elseif(NOT bus_hash STREQUAL "52ff001b67b5121afe964bb745132ece5648ae367744cec0a87edd12281ffdf8")
    message(FATAL_ERROR "Unrecognized AccessKit Unix cache source; refusing an unverified patch")
endif()
file(READ "${SB_C_SOURCE}/Cargo.toml" manifest)
string(FIND "${manifest}" "[patch.crates-io]" patch_section)
if(patch_section LESS 0)
    file(RELATIVE_PATH relative "${SB_C_SOURCE}" "${SB_UNIX_SOURCE}")
    string(REPLACE "\\" "\\\\" relative "${relative}")
    string(REPLACE "\"" "\\\"" relative "${relative}")
    file(APPEND "${SB_C_SOURCE}/Cargo.toml" "\n[patch.crates-io]\naccesskit_unix = { path = \"${relative}\" }\n")
endif()
# Same dependency version and graph; only its verified source becomes the local UI patch.
file(READ "${SB_C_SOURCE}/Cargo.lock" lock)
string(REPLACE "name = \"accesskit_unix\"\nversion = \"0.24.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"202f24df034a7476d07b7f74284de84f6d62aabd858dbe7ee9cad3b7ad6f8f9d\"\n"
    "name = \"accesskit_unix\"\nversion = \"0.24.0\"\n" lock "${lock}")
file(WRITE "${SB_C_SOURCE}/Cargo.lock" "${lock}")
